### ISSUE TITLE
Running gpt with `All Tracks.kmz` and `All Points.kmz` does not work

### ISSUE THREAD

**Issue by saibot8** [dave/gpt#1]
Hi Dave, thanks for writing this piece of software.

I am executing the Linux (x64) binary with `All Tracks.kmz` and `All Points.kmz` in the current directory and get the following error:
./gpt 
initialising
loading tracks kmz: opening "./GPT Master.kmz": open ./GPT Master.kmz: no such file or directory

Looks like they might have to merged into a single file? I am using v0.2.0

**Comment by dave** [comment]
Yeah it needs the GHT Master file... I think it is in the zip that Jan distributes?

**Comment by saibot8** [comment]
Thanks! It is.

**Comment by dave** [comment]
Did it work?!? I think you're the only person that's used it apart from me and Jan 😂

**Comment by saibot8** [comment]
It did! To be honest, I was not sure what this tool would do (it was just listed under "Track File Display and Processing Software" in the manual). Turns out it works well for re-producing the files that I already had when I started out. ;-)
Happy hiking!

**Comment by dave** [comment]
Yes that's right - this is what Jan uses to generate all the files... GPT Master is the master source of truth and all the files are generated by this tool. BUT one thing you might benefit from is that the descriptions in the GPX files are refreshed by scraping the wikiexplora site... So you'll get a more up-to-date version than the one distributed by Jan.
